Add user story
camaraproject/OTPvalidationAPI pull request #71
Opened 2024-07-09 09:01 UTC by bigludo7

#### What type of PR is this?

Add one of the following kinds:

* documentation

#### What this PR does / why we need it:

Add user story

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-07-15 08:44 UTC, jgarciahospital requested changes

2024-07-15 08:44 UTC, jgarciahospital commented on documentation/API_documentation/OTPValidationAPI_User_Story.md
> +| ***Pre-conditions*** |The preconditions are listed below:<br><ol><li>The Customer:BusinessManager and Customer:Administrator have been onboarded to the CSP's API platform.</li><li>The Customer:Busi
alllowing --> allowing

2024-07-15 08:44 UTC, jgarciahospital commented on documentation/API_documentation/OTPValidationAPI_User_Story.md
> +| ***Pre-conditions*** |The preconditions are listed below:<br><ol><li>The Customer:BusinessManager and Customer:Administrator have been onboarded to the CSP's API platform.</li><li>The Customer:Busi
Question: Include action end-user receives SMS code and provides to Customer:user application

2024-07-15 11:36 UTC, bigludo7 commented
Thanks @jgarciahospital 
All your comments considered in new proposal.

2024-07-17 09:33 UTC, fernandopradocabrillo commented on documentation/API_documentation/OTPValidationAPI_User_Story.md
> +OTP Validation user story is splitted in 2 steps. Both steps are mandatory to perform  this user story.
```suggestion
OTP Validation user story is splitted in 2 steps. Both steps are mandatory to perform this user story.

```

2024-07-18 09:00 UTC, jgarciahospital approved these changes

2024-07-18 11:06 UTC, fernandopradocabrillo approved these changes
LGTM

2024-07-18 11:30 UTC, merged